### ISSUE TITLE
你好，请教两个问题。

### ISSUE THREAD

**Issue by ASTARCHEN** [l294265421/algorithms-huffman#1]
1. 项目依赖的pom.xml 不能直接从maven中下载，如何获得呢？
2. 为何哈夫曼编码已有接口HuffmanAlgorithm，那么抽象类HuffmanAlgorithmAbstract的意义在什么地方？

期待您的回复。

**Comment by l294265421** [comment]
@ASTARCHEN 
1.可以在我的repository里搜common-tools和datastructure-common两个项目，拉到本地，就可以了。
2.HuffmanAlgorithmAbstract作为骨架类，用于实现那些所有实现HuffmanAlgorithm接口都需要实现的方法，这样，HuffmanAlgorithm的真正实现类就只需要关注实现HuffmanAlgorithm的逻辑了。可以阅读《Effective Java》中文版第二版第17条，如果有更好的理解或者建议，也欢迎指出。
同时，也非常欢迎提交pull request，把这个项目从对其它两个项目的依赖中剥离出来，方便学习

**Comment by ASTARCHEN** [comment]
3Q, 我觉得算法仍有改进的地方。谢谢你。
